function path=GetPath()
path(1,:)=char('../Dati/Esperto/Facile/prova.mat        ');
path(2,:)=char('../Dati/Medio/Facile/prova.mat          ');
path(3,:)=char('../Dati/Inesperto/Facile/prova.mat      ');
path(4,:)=char('../Dati/Esperto/Difficile/prova.mat     ');
path(5,:)=char('../Dati/Medio/Difficile/prova.mat       ');
path(6,:)=char('../Dati/Inesperto/Difficile/prova.mat   ');
path(7,:)=char('../Random_path_generation/JerkyPath.mat ');
path(8,:)=char('../Random_path_generation/SmoothPath.mat');